import { PrototypeState } from "../types/models";

const now = new Date().toISOString();

export function createSeedState(): PrototypeState {
  return {
    version: 2,
    activeUserId: "user_mom",
    activeFamilyId: "",
    activeChildId: "",
    users: [
      { id: "user_mom", nickname: "妈妈", avatarText: "妈" },
      { id: "user_dad", nickname: "爸爸", avatarText: "爸" },
      { id: "user_grandma", nickname: "外婆", avatarText: "外" },
    ],
    families: [
      {
        id: "family_demo",
        name: "暖暖一家",
        ownerId: "user_mom",
        createdAt: "2025-10-08T08:00:00.000Z",
      },
      {
        id: "family_grandma",
        name: "外婆的小院",
        ownerId: "user_grandma",
        createdAt: "2026-01-12T08:00:00.000Z",
      },
    ],
    members: [
      {
        id: "member_mom",
        familyId: "family_demo",
        userId: "user_mom",
        role: "OWNER",
        joinedAt: "2025-10-08T08:00:00.000Z",
        user: { id: "user_mom", nickname: "妈妈", avatarText: "妈" },
      },
      {
        id: "member_dad",
        familyId: "family_demo",
        userId: "user_dad",
        role: "ADMIN",
        joinedAt: "2025-10-08T08:10:00.000Z",
        user: { id: "user_dad", nickname: "爸爸", avatarText: "爸" },
      },
      {
        id: "member_grandma",
        familyId: "family_demo",
        userId: "user_grandma",
        role: "MEMBER",
        joinedAt: "2025-10-09T08:00:00.000Z",
        user: { id: "user_grandma", nickname: "外婆", avatarText: "外" },
      },
      {
        id: "member_grandma_home",
        familyId: "family_grandma",
        userId: "user_grandma",
        role: "OWNER",
        joinedAt: "2026-01-12T08:00:00.000Z",
        user: { id: "user_grandma", nickname: "外婆", avatarText: "外" },
      },
      {
        id: "member_mom_grandma_home",
        familyId: "family_grandma",
        userId: "user_mom",
        role: "ADMIN",
        joinedAt: "2026-01-12T08:10:00.000Z",
        user: { id: "user_mom", nickname: "妈妈", avatarText: "妈" },
      },
      {
        id: "member_dad_grandma_home",
        familyId: "family_grandma",
        userId: "user_dad",
        role: "MEMBER",
        joinedAt: "2026-01-13T08:00:00.000Z",
        user: { id: "user_dad", nickname: "爸爸", avatarText: "爸" },
      },
    ],
    children: [
      {
        id: "child_lele",
        familyId: "family_demo",
        creatorId: "user_mom",
        name: "乐乐",
        birthday: "2025-10-08",
        genderLabel: "宝宝",
        avatarColor: "#F0A58A",
        createdAt: "2025-10-08T08:00:00.000Z",
      },
      {
        id: "child_tangtang",
        familyId: "family_demo",
        creatorId: "user_mom",
        name: "糖糖",
        birthday: "2023-06-18",
        genderLabel: "姐姐",
        avatarColor: "#D991A2",
        createdAt: "2025-10-08T08:00:00.000Z",
      },
      {
        id: "child_anan",
        familyId: "family_grandma",
        creatorId: "user_grandma",
        name: "安安",
        birthday: "2026-02-14",
        genderLabel: "小表弟",
        avatarColor: "#87AAA0",
        createdAt: "2026-02-14T08:00:00.000Z",
      },
    ],
    assets: [
      {
        id: "asset_1",
        familyId: "family_demo",
        childId: "child_lele",
        creatorId: "user_mom",
        kind: "IMAGE",
        name: "清晨微笑.jpg",
        placeholderTone: "peach",
        createdAt: "2026-09-18T02:30:00.000Z",
      },
      {
        id: "asset_2",
        familyId: "family_demo",
        childId: "child_lele",
        creatorId: "user_dad",
        kind: "VIDEO",
        name: "第一次翻身.mp4",
        placeholderTone: "sage",
        createdAt: "2026-09-03T09:20:00.000Z",
      },
      {
        id: "asset_3",
        familyId: "family_demo",
        childId: "child_tangtang",
        creatorId: "user_grandma",
        kind: "IMAGE",
        name: "公园散步.jpg",
        placeholderTone: "rose",
        createdAt: "2026-08-28T08:00:00.000Z",
      },
      {
        id: "asset_4",
        familyId: "family_grandma",
        childId: "child_anan",
        creatorId: "user_grandma",
        kind: "IMAGE",
        name: "安安的午后.jpg",
        placeholderTone: "sage",
        createdAt: "2026-09-12T08:00:00.000Z",
      },
    ],
    entries: [
      {
        id: "entry_1",
        familyId: "family_demo",
        childId: "child_lele",
        creatorId: "user_mom",
        kind: "DIARY",
        title: "清晨的小小微笑",
        body: "醒来后对着窗边的光笑了很久。今天的阳光和你的笑一样柔软。",
        occurredAt: "2026-09-18",
        createdAt: "2026-09-18T02:30:00.000Z",
        updatedAt: "2026-09-18T02:30:00.000Z",
        assetIds: ["asset_1"],
      },
      {
        id: "entry_2",
        familyId: "family_demo",
        childId: "child_lele",
        creatorId: "user_dad",
        kind: "MILESTONE",
        title: "第一次自己翻身",
        body: "努力了好几次，终于成功翻过来，全家都在为你鼓掌。",
        occurredAt: "2026-09-03",
        createdAt: "2026-09-03T09:20:00.000Z",
        updatedAt: "2026-09-03T09:20:00.000Z",
        assetIds: ["asset_2"],
        customEvent: "第一次翻身",
      },
      {
        id: "entry_3",
        familyId: "family_demo",
        childId: "child_lele",
        creatorId: "user_mom",
        kind: "MILESTONE",
        title: "九月成长记录",
        body: "体检时记录了新的身高，长得很棒。",
        occurredAt: "2026-09-01",
        createdAt: "2026-09-01T03:00:00.000Z",
        updatedAt: "2026-09-01T03:00:00.000Z",
        assetIds: [],
        metric: {
          id: "metric_1",
          familyId: "family_demo",
          childId: "child_lele",
          creatorId: "user_mom",
          entryId: "entry_3",
          type: "HEIGHT",
          value: 72.5,
          unit: "cm",
          measuredAt: "2026-09-01",
        },
      },
      {
        id: "entry_4",
        familyId: "family_demo",
        childId: "child_tangtang",
        creatorId: "user_grandma",
        kind: "DIARY",
        title: "一起去公园",
        body: "糖糖一路都在认真观察树叶，还捡了一片最喜欢的带回家。",
        occurredAt: "2026-08-28",
        createdAt: "2026-08-28T08:00:00.000Z",
        updatedAt: "2026-08-28T08:00:00.000Z",
        assetIds: ["asset_3"],
      },
      {
        id: "entry_5",
        familyId: "family_demo",
        childId: "child_tangtang",
        creatorId: "user_mom",
        kind: "MILESTONE",
        title: "三岁两个月体重",
        body: "今天在家测量并记录。",
        occurredAt: "2026-08-18",
        createdAt: "2026-08-18T08:00:00.000Z",
        updatedAt: "2026-08-18T08:00:00.000Z",
        assetIds: [],
        metric: {
          id: "metric_2",
          familyId: "family_demo",
          childId: "child_tangtang",
          creatorId: "user_mom",
          entryId: "entry_5",
          type: "WEIGHT",
          value: 14.2,
          unit: "kg",
          measuredAt: "2026-08-18",
        },
      },
      {
        id: "entry_6",
        familyId: "family_grandma",
        childId: "child_anan",
        creatorId: "user_grandma",
        kind: "DIARY",
        title: "外婆怀里的午后",
        body: "吃饱以后安静地睡着了，小院里只有风吹树叶的声音。",
        occurredAt: "2026-09-12",
        createdAt: "2026-09-12T08:00:00.000Z",
        updatedAt: "2026-09-12T08:00:00.000Z",
        assetIds: ["asset_4"],
      },
    ],
    invites: [],
    exports: [
      {
        id: "export_demo",
        familyId: "family_demo",
        childId: "child_lele",
        creatorId: "user_mom",
        yearMonth: "2026-08",
        status: "CONFIRMED",
        partCount: 1,
        createdAt: "2026-09-01T08:00:00.000Z",
        expiresAt: "2026-09-08T08:00:00.000Z",
        confirmedAt: "2026-09-01T10:00:00.000Z",
      },
    ],
  };
}

export const seedGeneratedAt = now;
